slam_toolbox:
  ros__parameters:
    # Основные параметры
    map_frame: map                # Фрейм карты
    odom_frame: odom              # Фрейм одометрии
    base_frame: base_link         # Фрейм базы робота
    scan_topic: /scan             # Топик данных с лидара

    # Публикация преобразований
    publish_tf: true              # Включить публикацию преобразований между фреймами
    use_odom: true        # Отключаем использование одометрии


    # Параметры карты
    max_laser_range: 10.0         # Максимальная дальность лидара (в метрах)
    map_update_interval: 5.0      # Интервал обновления карты (в секундах)

    # Временные параметры
    transform_timeout: 0.2        # Время ожидания преобразований (в секундах)
    map_saver_timeout: 5.0        # Время ожидания сохранения карты (в секундах)

    # Дополнительные параметры
    use_scan_matching: true       # Использовать сопоставление сканов
    use_scan_barycenter: true     # Использовать центр тяжести сканов
